### ISSUE TITLE
Provide an optional dark theme, both for interface and for Wiki articles

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#10]
Windows Mobile users tend to prefer dark themes, white text on black or dark background. This should be a simple matter of providing some CSS classes and an option to apply them in the interface.

**Comment by mossroy** [comment]
I think it's an option that might be generic for all devices/platforms.
Such option exists in the Android Kiwix app, it's called "night mode".

For the UI, it is indeed simply switching CSS classes, but it might be more complicated for the article content itself. Because the CSS comes from the ZIM file

**Comment by Jaifroid** [comment]
Great, I'll raise the issue on kiwi-js, and contributions to this thread should go there from now on.

**Comment by Jaifroid** [comment]
The dark theme is now feature complete for Wikipedia files on kiwix-js-windows. I may support dark theme for other types of files through an inversion filter, but release 1.0 will ship with dark theme for major Wikipedia files only, which may or may not work on some wider Wikimedia files.
