### ISSUE TITLE
Make Setup (Installer)

### ISSUE THREAD

**Issue by xmha97** [kiwix/kiwix-js-windows#146]
Hi, Make setup (installer) for Windows 7.
![Installer](https://www.installaware.com/assets/images/suite-installer-wizard.png)

**Comment by kelson42** [comment]
@Jaifroid Do we really need this?

**Comment by xmha97** [comment]
Yes

**Comment by xmha97** [comment]
> @Jaifroid Do we really need this?

Yes, I need installer.

**Comment by Jaifroid** [comment]
@xmh97 It is better to use the Electron NSIS installer rather than the Suite Installer, because the former can easily be added to the build script for the Electron version (I use Electron-Builder). But could you explain why you cannot use the Portable version (NWJS) I currently provide for Windows 7? I mean this one: https://kiwix.github.io/kiwix-js-windows/kiwix-js-nwjs.html ? When you unzip that, you can simply launch the app with the provided shortcut(s), without having to install anything. I thought it was more convenient than an .exe installer and uninstaller.

**Comment by Jaifroid** [comment]
@xmha97 Have you also considered the PWA version? It is very lightweight and can be installed if you launch it in Chrome or in Edge Chromium. You will find an Install button under Configuration. Please try it out and see if it meets your needs (it also works offline once you've installed it): https://pwa.kiwix.org/www/index.html .

**Comment by Jaifroid** [comment]
@xmha97 The new release of the [WikiMed Electron version](https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html) version now includes an installable (Setup) build for Windows (properly signed) as well as the portable versions for Windows and Linux. Please try it out. Note that this version includes the full latest WikiMed archive in English. If you don't want that, wait for the release of the non-packaged version.

**Comment by xmha97** [comment]
> 
> 
> @xmha97 The new release of the [WikiMed Electron version](https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html) now includes an installable (Setup) build for Windows (properly signed) as well as the portable versions for Windows and Linux. Please try it out. Note that this version includes the full latest WikiMed archive in English. If you don't want that, wait for the release of the non-packaged version.

Thank you, but the app installed per user.
![image](https://user-images.githubusercontent.com/23485114/118051466-51933400-b396-11eb-81c5-9826da071ce5.png)
I want to install the app per machine (for all users)
In other words, I want the app to be installed in the %ProgramFiles%
![image](https://user-images.githubusercontent.com/23485114/118051496-61ab1380-b396-11eb-9c66-5d619186cb9e.png)

**Comment by xmha97** [comment]
Also, if possible, create `.deb` package for Linux.

**Comment by Jaifroid** [comment]
@xmha97 I have now changed the Windows installer options so that it gives you  a choice of "per user" or "per machine". It's a new installer on the same release https://kiwix.github.io/kiwix-js-windows/wikimed-electron.html, even though it has the same filename as before. I have also provided two Linux **deb** installer packages for you to test the appropriate one: amd64 (64bit) and i386 (32bit).

Let me know if this resolves this issue. I will release an Electron package of plain Kiwix JS (without WikiMed) in the next release cycle, and it will include these changes.

![image](https://user-images.githubusercontent.com/4304337/118162456-af686000-b418-11eb-8199-29f8a6a14715.png)

**Comment by xmha97** [comment]
Thank you.
The installer is working properly.
I'm waiting for a light version of Kiwix JS to be released.

**Comment by Jaifroid** [comment]
@xmha97 OK, I'll let you know when it's available.

**Comment by xmha97** [comment]
Dear @Jaifroid 
I have feedback for the Linux version (deb package)
The application has no icons after installation.
I also think the "Education" category is better than the "Utilities" category.
![image](https://user-images.githubusercontent.com/23485114/118390390-128a0a80-b644-11eb-8ad8-c9dae45e9cdb.png)

**Comment by Jaifroid** [comment]
OK, thanks, I'll look into it. I noticed the lack of an icon myself, though I thought I'd set one. Possibly has to be specific for Linux. I agree about category.

**Comment by Jaifroid** [comment]
@xmha97 I now have a somewhat experimental release of the "light" packages:

https://kiwix.github.io/kiwix-js-windows/kiwix-js-electron.html 

I managed to get an icon into the .deb packages, though I'm not 100% happy with the colour. Will change to darker colour in future, but I can't re-do everything just for an icon. Note that on Debian, there is an issue with all Electron packages (https://github.com/electron/electron/issues/17972#issuecomment-516957971), which means they have to be run with the `--no-sanbox` commandline switch (including the AppImage). On Ubuntu, it runs fine without that. There are instructions given on the release page.

![image](https://user-images.githubusercontent.com/4304337/119057888-37c0a500-b9c5-11eb-9a82-60d30c4ccf96.png)

**Comment by xmha97** [comment]
Thanks.
