### ISSUE TITLE
Offer (request)

### ISSUE THREAD

**Issue by Katran-399A** [kiwix/kiwix-js-windows#152]
Hello.
Please move the pop-up navigation buttons (forward, back, home) from the bottom of the program to the top (where the search bar is located).
So that it is the same as in the usual (familiar) browsers (Opera, Firefox, etc.).
Or make it possible to select this option in the program settings.
Thank you in advance.

**Comment by Jaifroid** [comment]
@Katran-399A There isn't much room at the top, especially on mobile! Also, for accessibility reasons, e.g. one-handed usage on mobile, we need to have accessible navigation buttons on the bottom bar, as this is closest to the thumb.

Maybe it could be an option to put them at the top or bottom, according to user choice. I'd have to think how that could be implemented in the limited space available.

**Comment by Katran-399A** [comment]
In the program settings, there is an option "Windows Desktop" - for this option, you can make the location of the buttons at the top.

**Comment by Jaifroid** [comment]
@Katran-399A This shouldn't be difficult to achieve as an option, but I dont' think it should be linked to Desktop display style, because that refers to the Wikipedia stylesheet (desktop vs mobile), not to UX. It should be a separate option: "Move navigation buttons to top bar" (in reality this will be swapping the navigation buttons for Configuration and Printer buttons (though the navigation buttons would go to the left of the search bar, like on Chromium browsers.

**Comment by Katran-399A** [comment]
"This shouldn't be difficult to achieve as an option, but I dont' think it should be linked to Desktop display style, because that refers to the Wikipedia stylesheet (desktop vs mobile), not to UX. It should be a separate option: "Move navigation buttons to top bar" (in reality this will be swapping the navigation buttons for Configuration and Printer buttons (though the navigation buttons would go to the left of the search bar, like on Chromium browsers."
Yes, I agree with you. It's just that I didn't accurately express my idea (difficulties in machine translation).

**Comment by Jaifroid** [comment]
@Katran-399A This feature is now available in master, and will gradually make its way into new releases. You can see screenshots of what it looks like below. Please note that the Kiwix icon top left is the Home button (it always has been), which is why I didn't move the secondary Home button that is on the bottom bar.

You can try out the code by visiting https://kiwix.github.io/kiwix-js-windows/ .  If you don't see the new option straight away, you may need to load the page, exit the page and reload it (possibly more than once). This is because that page caches the app's code as a PWA. **NB don't install the PWA from that page**: it is used only for development code, not final code.

![image](https://user-images.githubusercontent.com/4304337/120929123-badd3d00-c6df-11eb-9c38-e2f012c4d83f.png)

![image](https://user-images.githubusercontent.com/4304337/120929275-52db2680-c6e0-11eb-995e-ab4aee706f69.png)

I'll close this issue once the new code is available in the UWP app.

**Comment by Katran-399A** [comment]
Wish (suggestion). It is desirable that when the mouse cursor hovers over the "forward" and "back" buttons, these buttons somehow change. For example, in Opera, when you hover over these buttons, the background changes under them. 
But this is not strictly necessary, but at your discretion. Sorry for the machine translation.
Thank you for your work. We are waiting for the final code.

**Comment by Jaifroid** [comment]
@Katran-399A Actually this already works in Dark Mode (see screenshot -- I couldn't capture the mouse cursor, but it's hovering over the button). It should work in Light mode too, I'm not sure why not. I'll take a look, and thanks for pointing it out.

![image](https://user-images.githubusercontent.com/4304337/120937086-5fbd4180-c703-11eb-9516-fdb3431d8a48.png)

**Comment by Jaifroid** [comment]
Now also fixed in master :-) - for both :hover and :active css. Can be tested on [development PWA](https://kiwix.github.io/kiwix-js-windows/), but again, you have to allow it to upgrade to v1.4.0-RC2 (a message will appear in Configuration saying that it will be available on next launch of app).

![image](https://user-images.githubusercontent.com/4304337/120938826-c430ce80-c70c-11eb-8b8a-78f9c4796b66.png)

**Comment by Jaifroid** [comment]
@Katran-399A These changes are now published in Kiwix JS, WikiMed and Wikivoyage apps, versions 1.4.0, in the MIcrosoft Store or via `winget install kiwix`. See https://github.com/kiwix/kiwix-js-windows/releases.

Thank you for your bug spotting and suggestions.
