### ISSUE TITLE
Add second search method

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#165]
If you search for "list medieval", you will not receive any outcomes:

Kiwix JS PWA:

![20210709_155301](https://user-images.githubusercontent.com/71934042/125094141-4da03b80-e0d3-11eb-9985-3c326d1f5ee6.jpg)

In the Kiwix Android app you get:

![Screenshot_20210709-155217_Kiwix](https://user-images.githubusercontent.com/71934042/125094188-555fe000-e0d3-11eb-8d69-aaf33df70f60.jpg)

Both methods of searching have their advantages and disadvantages. In Kiwix Android, searching for "king" is tedious since you have to go through all the results initially to come upon the proper one:

https://user-images.githubusercontent.com/71934042/125091319-960a2a00-e0d0-11eb-9830-f07e75030f66.mp4

And in Kiwix JS PWA:

https://user-images.githubusercontent.com/71934042/125091444-b2a66200-e0d0-11eb-8227-aac3c9cf1f34.mp4

They both work great, but an additional setting that changes the type of search would be optimal so that we can willingly switch between the two.

What do you think?

**Comment by Jaifroid** [comment]
@Inbefortus Thank you for checking this.

The problem is that we can't currently support searching the full-text index in the ZIM. This is because it is compressed using Xapian, and we don't have a JavaScript port of Xapian. In fact it can be done with Emscripten (we already did that with XZ utilities and ZStandard, both of which we compiled to ASM or WebAssembly), but it is a lot of low-level coding to integrate the module into Kiwix JS / PWA.

The current plan is to compile libzim to JavaScript (using Emscripten), and @mossroy is working on that. In that case, we should get Xapian decoding "for free" as part of that compile.

What **would*** be possible now with our existing code is to enable a regular expression pattern search on a certain number of entries beginning with a key word. So, to use your example, it would be quite straightforward to enable a search like this:

`list.*medieval`

This would match 'list of medieval`, etc. However it would work by working through all entries that match `list` and testing them against the regular expression.. It wouldn't be possible to have a query like:

`.*medieval`

because the title index is ordered alphabetically, and we need to have a starting point. The index can be enormous, so it's not possible to scan it from beginning to end (a lot of decoding steps are involved just to retrieve the text of one title).

If we were to enable regular expression searching, it would have to be an option (or possibly a search beginning with a code like  `?:` (which itself is a regex).

**Comment by Inbefortus** [comment]
Fair enough. I get the point. 

If you plan to add anything (in regard to this), feel free to let me know. I would give it a shot!

**Comment by Jaifroid** [comment]
@Inbefortus I've added experimental support for regular expression searching, which enables you to do a search like in the image below. This is available in the development PWA here (don't install this, just test on the Web page):

https://kiwix.github.io/kiwix-js-windows/

Ensure it is updated to `v1.4.3-rc3`. If you see a message in Configuration saying that version is ready to load, you will need to exit the tab and load it again to get the version. You can check which version is running in the Information page (Configuration -> Info icon).

![image](https://user-images.githubusercontent.com/4304337/125190095-57d94b80-e233-11eb-9aaf-de717711f6dc.png)

**Comment by Jaifroid** [comment]
Usage notes:

* A regex search must have a prefix that is normal text, like `list` (this is so that the app knows where to start scanning forward from)
* A search will be treated as a regex if it contains `.*`, `.+`
* You can also use a more complex regular expression by enclosing it in `(?:)`, e.g. `list(?:.*medieval.*India)`
* The regular expression part will be matched in a case-insensitive manner (the prefix, `list` in this case) will attempt pseudo-case-insensitivity, but it limits the number of combinatiions, so it's best to use lowercase
* The algorithm will scan forward from each variant of prefix (e.g. `list`, `List`, `LIST`) up to a maximum of 250,000 titles
* The algorith will stop scanning at the earliest of:
  + prefix no longer matches found title
  + The maximum number of search results set in Configuration (default 25) have been found
  + 250,000 titles have been scanned for the prefix variant
* If regex mode is detected, then **the whole search must be a valid regular expression**, so, for example it will not search for `list (.*medieval` because the entire search string cannot be compiled to a regular expression (invalid parenthesis without close parenthesis.

These rules may sound a bit complex, but they are hopefullin intuitive. The most obvious use case is `.*` or `.+`, i.e. a wildcard function. Please note that I have not enabled a syntax like `list medieval`, because that does not tell the algorithm that we want a regex search.

I could set the search window higher that 250,000, but that is only really needed for very large ZIM archives. It seems like a good number for English Wikipedia for extreme cases like `list of`, for which there are hundreds of thousands of results, but obviously it won't return absolutely every result possible.

**Comment by Jaifroid** [comment]
@mossroy Please try out this functionality and let me know if you'd like me to add it to Kiwix JS upstream. In the process of doing this, I found a few optimizations of the search algorithm (some things that do not make sense, like continuing to search a variant even after the prefix no longer matches, due to lack of a simple test to stop the search).

**Comment by Jaifroid** [comment]
There is some debugging in console.debug (open Dev tools and set the debugging level to all if it is not already). It shows each variant searched, and the number of titles scanned. If it stops after scanning only a couple of titles, say, it is because the prefix no longer matched.

I am thinking of setting the search window to 10,000 * max_search_results set in Configuration. It is arbitrary but proportional to number of results requested.

Another sample search, this time of WikiMed, below.

![image](https://user-images.githubusercontent.com/4304337/125191025-421a5500-e238-11eb-8d57-726b58cce51f.png)

**Comment by Inbefortus** [comment]
@Jaifroid Good job! This functions as estimated and is positively an efficacious solution. This will be a tremendous help in various scenarios. I will make much use of it.

Thank you very much for your contributions.

**Comment by mossroy** [comment]
> @mossroy Please try out this functionality and let me know if you'd like me to add it to Kiwix JS upstream.

It's cool, and seems to work well. But it's a feature for geeks only (no offense, I'm one too! ;-) )
I'd prefer to wait for the full-text search with emscripten (if we manage to make it work), which seems more user-friendly to me

**Comment by Jaifroid** [comment]
OK, no problem! I'll see if I can add the simple optimizations without the feature itself.

**Comment by Jaifroid** [comment]
This feature is now nearing completion. I have made it possible to start a search with a wildcard. This is extremely useful in Stackexchange ZIMs, for example, where you want to search for all questions containing specific text (see example from Philosophy Stackexchange ZIM in screenshot). Yes you can use Tags in Stackexchange to approximate this, but that only works for general topics that have been tagged.

It is also useful for Gutenberg, TED talks, and any ZIM with a reasonable number of titles. It works fine in subsets of Wikipedia, like WikiMed, but of course starting a search string with a wildcard is useless in full English or German Wikipedia (because the search will start at the very beginning of the title index and will give up by design after `maxSearchResultsSize * 10^4` title scans - there are millions of titles!).

I have also added useage / syntax notes in 'About'.

![image](https://user-images.githubusercontent.com/4304337/125633676-94602737-f27c-4795-bf8e-67d7dbda2896.png)

**Comment by Jaifroid** [comment]
New code can be tested in development PWA - https://kiwix.github.io/kiwix-js-windows/ .

**Comment by Jaifroid** [comment]
This fix is now published.
