### ISSUE TITLE
Image and text not placed accurately

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#175]
The image is too much to the left, although it is originally precisely in the center. The accompanying text is also not placed accurately. This is the same case almost everywhere. Whether desktop or mobile, it doesn't matter.

I compared 2021-07 ENWP 0.8 with 2021-03 ENWP in Kiwix JS PWA.

Left: 2021-03 ENWP (accurate)
Right: 2021-07 ENWP 0.8 (inaccurate)

![ZomboDroid 23072021115425](https://user-images.githubusercontent.com/71934042/126769861-9df9d27f-0b87-4c60-9150-344ca4f754a6.jpg)

2021-07 ENWP 0.8 in the Kiwix Android app looks fine:

![20210723_115241](https://user-images.githubusercontent.com/71934042/126770194-312acb95-c41f-4b6d-a163-c545439ddb29.png)

This may look harmless, but could perhaps be related to other potential flaws?

I wasn't sure enough if I should report this here or at mwoffliner.

**Comment by Inbefortus** [comment]
For some reason, this article has been spared: https://en.wikipedia.org/wiki/J%C3%BCrgen_Klinsmann

An in-depth comparison would be a good approach. This might help you find the cause.

**Comment by Jaifroid** [comment]
@Inbefortus For speed, the app uses its own modified copies of a Wikimedia ZIM's CSS unless the user turns off this option in Configuration. This means that some CSS is not identical in all the different language-based ZIMs. If the circled setting in the screenshot below is turned off, then the app will use the CSS it finds in the ZIM (this will be a bit slower at first, but the app caches that CSS, so it only affects the first time a CSS file is needed). However, note that if you have the Desktop style turned on, then the app must use some of its own CSS files in order to make the transformation (because Desktop CSS is not included in ZIMs produced since about 2019 or maybe earlier). You should also know that there are differences between the placement and centering of text, images and infoboxes between mobile versions and desktop versions, so if you use Desktop style all the time, you will never have exact fidelity. For the best fidelity to the Mobile view of Wikipedia online, ensure "Select style automatically" is set (screenshot below) and uncheck "Use locally cached display styles". The last thing to say is that the styling system in this app is a legacy feature which I hope to modernize and make more reliable in future versions of the app. But for the moment it is what allows the transformation between Mobile and Desktop styles in Wikimedia ZIMs.

![image](https://user-images.githubusercontent.com/4304337/127765504-ead89feb-d6ea-436e-b4a9-410803c19fea.png)

**Comment by Inbefortus** [comment]
@Jaifroid Thank you for your detailed declaration. I am aware of the differences, I just wanted to know concretely why a build that is months old (2021-03) is (setting-independent) displayed insignificantly better than a build that is over a week old (2021-07). If anything, the structure of the ZIM has changed not too long ago? But it doesn't matter anyway, because no one notices, and it doesn't influence the usage of the app in any way!

**Comment by Jaifroid** [comment]
@Inbefortus I've pushed some style modifications that should fix this issue. To test them out, visit https://kiwix.github.io/kiwix-js-windows/ (the dev PWA). You will need to let it update to v1.6.1-rc1, which may involve switching between Config and Home and back again until you see a banner saying v1.6.1-rc1 is ready. You then exit (completely) and reload the page (not enough to do page refresh) and it will tell you v1.6.1.-rc1 is running. Then you can test.

![image](https://user-images.githubusercontent.com/4304337/127813333-44c1740d-edab-4f9a-8ffb-bbee5b5c290b.png)

**Comment by Inbefortus** [comment]
@Jaifroid I can confirm that this has been fixed. Thank you for taking the time to fix this!

**Comment by Jaifroid** [comment]
Thanks for the confirmaiton. I'll close this once the fix has made its way into a published app.

**Comment by Jaifroid** [comment]
This is now in v1.6.1, available in the PWA.
