### ISSUE TITLE
HTML displayed on top of articles

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#18]
I deal with the following ZIM file:
http://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_novid_2017-10.zim

On almost any article ("Vertigo" for example), I see HTML code at the top of article. The rest of the article display quite nicely.

**Comment by Jaifroid** [comment]
Yes, this issue has crept in with the evolving format of the "novid" file types. I've only just noticed it with the very latest ZIMs. The novid ZIMs produced in August do not have this issue. Therefore there must be some change in format that I will need to work around. I confirm this bug and will fix.

**Comment by kelson42** [comment]
The ZIM format has not changed... but the HTML might have changed... In the last six months we have done two major things on mwoffliner:
* We have introduce the "mobile layout" (a mobile CSS/DOM) - I suspect the problem is related to that
* We have massively reorganise the code to make it easier to maintain

... maybe the HTML is somehow invalid, but this is the first time I see that.

**Comment by Jaifroid** [comment]
Great, that's helpful info, @kelson42 . I suspect it is the mobile layout, as you say. I need to do some testing with these October ZIMs, but I think the fix will be simple and may speed up the display of pages with these ZIMs (by caching the CSS).

**Comment by Jaifroid** [comment]
@kelson42 I've been investigating this issue, and it's caused by the fact that the new "novid" ZIMs that have appeared since October (possibly also September) are not referencing correctly (I think) the location of some of the stylesheets. This could *potentially* be a problem for Kiwix JS ( @mossroy ) as well as for Kiwix JS Windows, because both apps test for CSS contained in the ZIM using the following Regular Expression:
 
`var regexpMetadataUrl = /^(?:\.\.\/|\/)+(-\/.*)$/;`

You can see that this regex will not match the first three `link href` values that are contained in the header of this html file whereas it does match the last three:
```
<link href="s/css_modules/ext.kartographer.link" rel="stylesheet" type="text/css">
<link href="s/css_modules/ext.kartographer.style" rel="stylesheet" tyope="text/css">
<link href="s/css_modules/skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mobile.app.pagestyles.android|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/mobile.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/content.parsoid.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/inserted_style_mobile.css" rel="stylesheet" type="text/css">
```
(Source: Asia.html page from `wikivoyage_en_all_novid_2017-10.zim`.)

As you can see, the issue is that the hrefs are missing "../-". This pattern is used by both Kiwix JS and Kiwix JS Windows to detect built-in as opposed to external stylesheets, images, etc., and the above regex requires that it match either "../" or "/" at least once followed by "-/" in order to recognize the pattern.

Now, I can and will temporarily work around this in Kiwix JS Windows by recognizing "s/" and adding in the missing path, but I wonder if this is a bug in the scraper, or whether those styles are in fact stored in "/s" as opposed to "../-/s". It seems that various clients could potentially miss those styles if the address is wrong.

Any thoughts?

**Comment by Jaifroid** [comment]
@kelson42 I've just noticed another problem is that those "kartographer" styles don't have the customary ".css" extension. Compare the above to the following from the July Wikivoyage ZIM:
```
<link rel="stylesheet" href="../-/s/style.css">
<link href="../-/s/css_modules/ext.kartographer.link.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/ext.kartographer.style.css" rel="stylesheet" type="text/css">
``` 
(Source: Bangkok.html from `wikivoyage_en_all_2017-07.zim`.)

As you can see, in the previous ZIM, both files are referenced with .css extensions and with the correct path for internal stylesheets. So something is a bit wrong with the more recent ZIMs!

**Comment by Jaifroid** [comment]
Further info:
The archive `wikipedia_en_medicine_novid_2017-10.zim` contains the following stylesheet entries, with the first three displaying the same issue (incorrect path, missing .css extension) as in the latest Wikivoyage archive, but affecting different stylesheets:
```
<link href="s/css_modules/ext.cite.a11y" rel="stylesheet" type="text/css">
<link href="s/css_modules/ext.cite.styles" rel="stylesheet" type="text/css">
<link href="s/css_modules/skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mobile.app.pagestyles.android|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/mobile.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/content.parsoid.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/inserted_style_mobile.css" rel="stylesheet" type="text/css">
```

**Comment by kelson42** [comment]
@Jaifroid I suspect all of part of these problem have been fixed recently in mwoffliner. Let see if we still see the problem with newly generated ZIM files. Thx anyway for the workaround.

**Comment by Jaifroid** [comment]
Thanks @kelson42 

Commit https://github.com/kiwix/kiwix-js-windows/commit/b9c8f87ba8cf9970e31cc9fc7ece0393a81453c4 works around the issue by allowing the app to find the missing stylesheets in its own local cache (they are very common stylesheets). However, if I turn off the option to use the locally cached styles (in the app's settings) then the stylesheets cannot be found at the corrected location. Let's see if the fix at mwoffliner sorts this out further or not.

I'll keep this open till we get a new ZIM to try.

**Comment by kelson42** [comment]
Workaround seems to work fine. @Jaifroid Give me a few days to upload newly made ZIM files so we can check the problem is also fixed at the root.

**Comment by kelson42** [comment]
@Jaifroid Here is a newly generated ZIM file. Hope that work *without the workaround* http://download.kiwix.org/zim/wikipedia/wikipedia_fr_tunisie_2017-12.zim

**Comment by Jaifroid** [comment]
Excellent, I'll test as soon as I can.

**Comment by Jaifroid** [comment]
@kelson42 , I can confirm that the headers produced in the new ZIM look like this _before_ application of the workaround:
```
<link href="../-/s/css_modules/ext.kartographer.link.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/ext.cite.a11y.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/ext.kartographer.style.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/ext.cite.styles.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mobile.app.pagestyles.android|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/mobile.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/content.parsoid.css" rel="stylesheet" type="text/css">
<link href="../-/s/css_modules/inserted_style_mobile.css" rel="stylesheet" type="text/css">
```
All the URLs conform to the correct schema for built-in stylesheets and the app is able to find them in the ZIM and add them to the blob cache. Some of the stylesheets are empty or placeholders (one of the kartographer ones for example), but I understand that's intentional.

In any case, I think this confirms that the error in the October and November ZIMs is fixed!

I'll keep this workaround until those ZIMs are no longer so prominent. It's a single regex and doesn't do any harm, and will stop complaints from people downloading the previous ZIMs. Thank you for working on this so speedily.
