### ISSUE TITLE
No substring search in titles (vs Android, IOS, and Full Desktop versions)

### ISSUE THREAD

**Issue by cjohnsto-nz** [kiwix/kiwix-js-windows#195]
The search on this version, and the browser extension, does not search for substrings within Titles unless it matches the start of the title.

Any chance this is an easy fix?

**Comment by Jaifroid** [comment]
@cjohnsto-nz In Kiwix JS PWA / Windows, you can search with wildcard .* or even a regular expression. There's a full explanation of how this works in Config -> Title Search -> See Usage (circled area in screenshot below). Does this cover your needs? Please note that it's not technically possible (yet) in the JS variants of Kiwix to do full text search of the contents of all articles, though it is something we plan.

Just note with the wildcard that in large ZIMs you will get much faster results if you don't begin your search with the wildcard, but only use it after, say, a starting word. Otherwise the app has to search through every single title entry in the ZIM, which can be millions and millions of searches in large ZIMs...

![image](https://user-images.githubusercontent.com/4304337/133977779-67eb098e-9945-4cd6-b1c8-aefc7d72d716.png)

**Comment by Jaifroid** [comment]
So, I think we can deem the issue to be resolved. There is substring search for titles, and it is documented, in Kiwix JS Windows.
