### ISSUE TITLE
Some images not shown in mobile templates

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-js-windows#201]
Example article: Moon

Desktop:

![20211016_230003](https://user-images.githubusercontent.com/71934042/137601949-592073b2-86ab-471d-8642-a751d2bf5fa2.jpg)

Mobile:

![Screenshot_20211016-224934_Samsung Internet](https://user-images.githubusercontent.com/71934042/137601828-82c0d02c-72b7-4aa1-a3b8-98ec0d445646.jpg)

**Comment by Jaifroid** [comment]
@Inbefortus Please try the latest version of the development PWA, where I have put a fix in for this issue. The version number is 1.7.7-rc4. Ensure the PWA has updated to this version.

If you are in jQuery mode, this should just work (if the option to display hidden elements is on). If you are in Service Worker mode, then you will also need to turn on "Allow image manipulation", as this allows the app to processes images, change style rules, etc. When a user is in SW mode, and turns on "Display hidden block elements", then it will also turn on the option "Allow image manipulation", and will display a warning notice that it has done this. If you turn off image manipulation in SW mode, then you'll still see hidden elements, but not the zero-width hidden images inside those elements!

Please note that if you switch to SW mode from jQuery mode, then the option to display hidden elements and image manipulation will be turned off (and you'll be warned about it). This is because I want the user to make a conscious decision to turn this option back on in SW mode, and not to leave it on by accident. It can interfere with dynamic content in non-Wikipedia ZIMs.

**Comment by Inbefortus** [comment]
@Jaifroid I can confirm you fixed this. Nice!
