### ISSUE TITLE
Small disply problem with the bottom bar (on the right)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#22]
![wp_ss_20171130_0001](https://user-images.githubusercontent.com/1029718/33453506-272b05e6-d616-11e7-850f-46e48794e2a0.png)

The bar is not display properly up to the right border

**Comment by mossroy** [comment]
It looks like the same issue as #16

**Comment by Jaifroid** [comment]
This is the same or similar bug to: #16 (Random Bootstrap display bug after window resize). However, good to keep this one open as it has the screenshot clearly showing the issue. I have not been able to determine when exactly this happens. It's a Bootstrap issue. @Mossroy and I also ran into it on Kiwix JS on this PR:
https://github.com/kiwix/kiwix-js/pull/303#issuecomment-333404901 
... which is why we haven't accepted the PR yet.
We're a bit puzzled. Needs investigation.

**Comment by kelson42** [comment]
Sorry for the duplicate :(... Bootstrap 4.0 is in beta, maybe time to give a try ?

**Comment by Jaifroid** [comment]
If it's not too radically different! But I think getting it right over on Kiwix JS, with Bootstrap 3 if possible, will help solve the problem here. It may be a "simple" thing (I mean a little tweak, because CSS / HTML interaction is never simple).

**Comment by mossroy** [comment]
I agree with @Jaifroid 
I think it's more probably a misuse of bootstrap (on our side) than a bootstrap bug.
We make a very basic use of bootstrap

**Comment by kelson42** [comment]
@Jaifroid @mossroy I think the problem might be easily be made "invisible" by putting this in the CSS

```
#navigationButtons {
    background-color: rgba(217,237,247,0.8) !important;
}

```
That said the buttons are also not centered properly... but this is another problem.

**Comment by Jaifroid** [comment]
I'll tinker this weekend @kelson42 . I think I need to do more work on the UI, because the search bar at the top has wrapped down in the screenshot above, which is an issue with the resolution of the device you're using. It should look like this:

![image](https://user-images.githubusercontent.com/4304337/33471625-27e68e2e-d666-11e7-9fc0-2d3f8bcf1b38.png)

There is enough space for a small search bar in the top row. I have installed Kiwix JS on a Lumia 920 hacked to run Windows 10M, and it has the same issue as you're showing above, so I have a basis for testing and, hopefully, fixing.

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js-windows/commit/9881eb295c5229b909a291a2767a2445301d2111 is a bit of a quick-fix which comments out some of the logic designed to deal with smaller displays, and which seems to have an error in it: the bootstrap columns do not add up to the correct total value when the display is smaller.

I have tested on a Lumia 920 and a Lumia 1020 (hacked to run Windows 10 Mobile), and the display issue seems to be "fixed" for those (very old) devices. This is more of a workaround than a proper attempt to make the small-screen logic work as intended, but these small displays seem fully usable, and more modern large-display devices are completely unaffected by this.

I shall test on some VM's before submitting to the store.

**Comment by kelson42** [comment]
@Jaifroid If you upload an .apxupload somewhere, I can also test it... as I had the problem too.

**Comment by Jaifroid** [comment]
Thank you @kelson42 , I've tested this .appxbundle on the physical devices I have and a VM (and made some changes to accommodate the VM's very narrow display). On first startup the buttons on the bottom bar may seem to stack vertically, but they should correct themselves once the appropriate bit of JavaScript runs (almost instantaneously). Here is the .appxbundle:

https://github.com/kiwix/kiwix-js-windows/blob/master/AppPackages/KiwixWebApp_0.9.2.0_Test/KiwixWebApp_0.9.2.0_AnyCPU.appxbundle 

Or if you prefer go to https://github.com/kiwix/kiwix-js-windows/tree/master/AppPackages and choose the 0.9.2.0_Test directory. Many thanks!

**Comment by kelson42** [comment]
Seems to be fixed to me :)
