### ISSUE TITLE
Add a cookie entry so that the app (optionally) remembers the last visited page and returns to it on next launch

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js-windows#25]
This would be useful in at least these cases:
 
* User accidentally exits the app and has to re-launch it to continue reading the article
* User leaves the app to come back to it later

This should be an option in the interface, so that the user can turn the behaviour on or off, since it has privacy implications. Cookie must *not* remember the last-visited page if the user has turned the option off.

Such an option, if developed, would need to be added to the Privacy Policy.

**Comment by mossroy** [comment]
Good idea.
We already discussed a bit that subject in https://github.com/kiwix/kiwix-js/issues/127
Storing/reading the info in a cookie is easy.
The problem is to be able to open the ZIM file without user interaction : it's not possible in a standard browser (blocked by security policies), unless the ZIM file is bundled with the source code (like in a "custom app"). But it might be possible with your Windows-specific APIs

Regarding the privacy implications, the cookie is only stored and read locally. It's worth mentioning it for transparency reasons, but might not be a big issue.

**Comment by Jaifroid** [comment]
This is now implemented with https://github.com/kiwix/kiwix-js-windows/commit/1e41faa94576e5d956c8abe910ec74b192b475e1 . I also added a "Privacy Settings" panel which includes the option to turn this off (which erases the cookie entry and prevents it being set on page visits).

![image](https://user-images.githubusercontent.com/4304337/34070899-4299b97a-e265-11e7-8ed9-c8b11ae489cb.png)

**Comment by kelson42** [comment]
Any chance to have this in kiwix-js... or I'm just not understanding that this is not possible for any (security?) reason?

**Comment by Jaifroid** [comment]
@kelson42 The code is easy to add to kiwix-js, but as @mossroy mentions above, currently Kiwix-js can't open a ZIM file on launch without the user explicitly picking it. I think this option only makes sense when the app can open both the last-used ZIM file and the last-visited page automatically without user intervention.

https://github.com/kiwix/kiwix-js/issues/292 discusses a possible way of automatically opening a ZIM, and if we can implement that, then this enhancement should definitely be added in there.

**Comment by kelson42** [comment]
@Jaifroid Thx for the answer

**Comment by Jaifroid** [comment]
This has now been pushed to Release 0.9.6 Beta.
