### ISSUE TITLE
DOMException after selecting a folder that is a symlink to another disk, with Chromium snap on Ubuntu

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js-windows#283]
Discussion had started in https://github.com/kiwix/kiwix-js/issues/656#issuecomment-1207218566
I was testing the File System Access API on Chromium 104 on Ubuntu 20.04 (using the snap provided by Ubuntu)
If I select my usual directory where my ZIM files are located, it displays an error in the log:

```
Uncaught (in promise) DOMException: A requested file or directory could not be found at the time an operation was processed.
Promise.then (async) 
  | iterateAsyncDirEntryArray | @ | app.js:2987
  | processNativeDirHandle | @ | app.js:3018
  | (anonymous) | @ | app.js:2917
  | Promise.then (async) |   |  
  | pickFolderNativeFS | @ | app.js:2914
  | (anonymous) | @ | app.js:1168
```

and it does not display any ZIM file.

If I move all the content in a local directory, or directly point to the other disk, it works well.
So I suspect it could come from the fact that my usual directory is in fact a symlink to a directory in another disk.

It might be not related to kiwix-js-windows code

**Comment by Jaifroid** [comment]
This may be a limitation of the API. I enumerate files in the directory using the API, not using any special technique. In fact, given the sandboxed nature of access to a directory under this API, it doesn't really surprise me that it would be forbidden to follow simlinks to another directory for which permission hasn't been granted.

What I suggest is that I handle it by detecting the error and giving some feedback to the user.

**Comment by Jaifroid** [comment]
OK, I've found out that there is indeed an inconsistency in the API, and a corresponding issue in the spec, and bug report on Chromium. See:

* https://github.com/WICG/file-system-access/issues/113
* https://bugs.chromium.org/p/chromium/issues/detail?id=1231268

Precisely the issue you noted, @mossroy, is mentioned in the second: "Linux: trying to open a symlink errors because the file cannot be found".  I'm marking this as upstream, but it could still be useful to inform the user.

**Comment by Jaifroid** [comment]
As there's really nothing I can do to fix this upstream issue, I'm closing for now.
