### ISSUE TITLE
Repo name is misleading

### ISSUE THREAD

**Issue by Rexadev** [kiwix/kiwix-js-windows#296]
Also Read.me should link to Reader, MedWiki,[Wikivoyage](https://github.com/kiwix/kiwix-js-windows/releases/tag/v2.1.5-Wikivoyage) separately

**Comment by Jaifroid** [comment]
@Rexadev Could you elaborate on why it's misleading? Are you referring to the fact that I publish packages for Linux and also a PWA as well as Windows? The history is that this Repo began as a port of Kiwix JS (upstream) to the UWP frawework, which is Windows only. I then branched out by adding Electron and PWA versions, which are of course multi-platform.

**Comment by Rexadev** [comment]
>Could you elaborate on why it's misleading? 
kiwix-js-windows "Windows" it also has reader for Linux and a PWA.

**Comment by Jaifroid** [comment]
@kelson42 @mossroy what is your view of this? Historically my focus has been Windows, but it has become broader with the PWA and Electron. An option would be to rename the repo `kiwix-js-pwa` (so long as a redirect could be put in from `kiwix-js-windows`), but some things would break (the winget repository which depends on GitHub releases, probably the update API for Electron, a lot of public links), so I'd need to prepare and migrate, but it would be doable.

**Comment by Rexadev** [comment]
pwa is cloud de misleading how about `kiwix-JS`. It is a PWA but that doesn't sound like a client for windows and linux.

Also give direct download links in ReadMe in a table. releases page is clustered
@Jaifroid

**Comment by Jaifroid** [comment]
@Rexadev We already have upsteam a client called Kiwix JS (https://github.com/kiwix/kiwix-js), and it is focused currently on Browser Extensions. This Repo is downstream of that, and shares a lot of code (they are co-developed). There are a lot of packages here for each release, and I can't link to all of them from the readme page, which is why I link to Releases from there. Releases are "cluttered" because there are a lot of packages in each release, but there is an organized table that tries to guide users according to OS and flavour of OS. I can try to simplify the pathway in the README and can put a table at the top to guide users who want to find a package quickly.

**Comment by Rexadev** [comment]
`Kiwix-JS-App`

**Comment by Jaifroid** [comment]
Closing in favour of #474.
