### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by xmha97** [kiwix/kiwix-js-windows#302]
Kiwix JS is an electron app.
Please make a portable version: (like LosslessCut)
https://github.com/mifi/lossless-cut/releases/tag/v3.44.0
https://github.com/mifi/lossless-cut/releases/download/v3.44.0/LosslessCut-win-x64.exe

**Comment by Jaifroid** [comment]
@xmha97 Are you aware that we have two portable versions that are zipped? You can unzip and use anywhere with the provided shortcuts to launch, including on a thumb drive, etc. I guess what you're asking for is a self-extracting version, i.e. one that extracts the code to a temporary location and launches it when you run the executable. That's how these portable Electron packages work. I can indeed build such a version (of the base app), but I do find it's slower to launch than the Zipped versions, because of the need to extract the files to TEMP on each startup.

**Comment by xmha97** [comment]
Thank you for your response.
I prefer a single file version, like the AppImage versions on Linux.
I will run this version on SSD storage and it won't run slow.

**Comment by Jaifroid** [comment]
OK, I'll build one and you can test it.

**Comment by Jaifroid** [comment]
@xmha97 So I did a quick test build. You'll find it added to the assets in this release: https://github.com/kiwix/kiwix-js-windows/releases/tag/v2.1.8-E , and the direct download link is https://github.com/kiwix/kiwix-js-windows/releases/download/v2.1.8-E/Kiwix-JS-Electron-Portable-2.1.83-E.exe . This is built for 64bit architecture, as I thought it might be marginally faster than 32bit. If you need 32bit, let me know.  _**N.B:: Windows Smart Screen will probably block access to this file, because it is "not commonly downloaded" (yet)**_: you will need to click on the three dots next to the unsafe notification and click through to "Keep" and "Keep anyway".

In terms of launch speed, I have to warn you that it takes about 30 seconds to launch on a high-end machine (and not just the first time, each time!), which is the main reason I don't usually build this version. It's much faster to run one of the portable zipped versions ([Electron](https://github.com/kiwix/kiwix-js-windows/releases/download/v2.1.8/Kiwix-JS-Electron-2.1.8-E.zip), [NWJS](https://github.com/kiwix/kiwix-js-windows/releases/download/v2.1.8/kiwix_js_windows-2.1.8-N-win-ia32.zip)), once you've unzipped them. They don't need to be installed, but they do need to be unzipped.

If it's genuinely useful to you, I can add it to regular releases.

**Comment by Jaifroid** [comment]
@xmha97 I found a way to make this launch faster: by enabling ASAR packing inside the Electron app. There is a new version for you to test here: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.1.8-E/Kiwix-JS-Electron-Portable-2.1.84-E.exe .
This one launches in about 10 seconds, so much more useable.

**Comment by Jaifroid** [comment]
This issue is fixed in release https://github.com/kiwix/kiwix-js-windows/releases/tag/v2.1.9. There is now a signed version of a portable executable for Windows.

**Comment by xmha97** [comment]
Many thanks
