### ISSUE TITLE
Custom apps should *not* be able to open custom ZIM file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#38]
* The select widget should be removed (or blinded)
* The app instructions shoudl be adapted
* The association between the app and *.zim(aa) should be removed to avoid to propose Wikivoyage app as an app able to deal with ZIM files.

**Comment by mossroy** [comment]
If I understood correctly, the title of this issue should be renamed to something like "Custom apps should NOT be able to open another ZIM file)"?

**Comment by kelson42** [comment]
@mossroy yes, sorry. I have fixed it.

**Comment by Jaifroid** [comment]
These "features" are due to the architecture of the app which is basically just Kiwix JS Windows set to open whatever ZIM it finds in its internal storage area. I agree, however, that it's a bit confusing especially for naïve users.

If I hide the Select functionality (and yes, I can remove the association with *.zim and *.zimaa ), then I also need to hide the Download functionality, no?

What I would like would be to redirect users to Kiwix JS Windows if they want to use the Mobile app to download other ZIMs, so maybe the Download button could open an info panel redirecting the user.

I'd like to keep changes as minimal as possible (hiding rather than removing features) so as not to have to maintain separate apps which might start to diverge in features.

**Comment by kelson42** [comment]
Yes, everything related to open custom ZIM file should be removed.

I fully agree with you that that content should better be hidden than removed (you could introduce a special CSS class for example?). Make rewording as small as possible to keep the whole easy to maintain. Our experience with Android has shown us, this is doable quite easily.

Yes, routing people to Kiwix JS for Windows seems to be a good approach.

**Comment by Jaifroid** [comment]
I've implemented the code for this in source, but I have not yet rewritten the descriptions. This is to follow.

The code leaves an *option* (with suitable warnings) to unhide the hidden selectors in the expert settings. My reasoning for this is that someone may wish to download Wikivoyage in other languages as well as in English, and I do not currently have the time or resources to make custom apps for every language, though I could consider French and Spanish if we introduce internationalization in Kiwix JS.

**Comment by Jaifroid** [comment]
Instructions now rewritten.

**Comment by kelson42** [comment]
@Jaifroid Thank you very much. It's true that half-way custom apps (with some options to download a content in other languages or with more/less medias, ...) is an open topic. I do not know what would be the best approach myself :(
