### ISSUE TITLE
Systematic crash on WikiMed article "A/Hodgkin-Huxley_model.html"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#49]
With my Lumia, the app always crash with that article. Because the app restarts automatically at the last visited article, it crashes in loop :(

**Comment by Jaifroid** [comment]
Oh dear. I see the issue is that the page has lots of equations on it, but this version of WikiMed does not have the alt text that enables the app to use MathJax. The problem is that decompressing SVGs is extremely taxing on xzdec.js. It uses a huge amount of memory. This article loads fine on my Lumia 950XL which has 3GB of RAM. I have attempted to fix the SVG problem by limiting the number of SVGs that get sent to the decompressor at a time, and I could try limiting them even more (they're currently sent in batches of 3). That might do the trick on lower-spec devices. But what would really fix the issue would be a fix for https://github.com/openzim/mwoffliner/issues/164 .

**Comment by kelson42** [comment]
@Jaifroid Yes, was my guess too. My device has 1GB (in total of memory). I would suggest to try to reduce the batches from 3 to 2 and if this is still not enough even only 1 at a time to see if that fix the problem... even if this slow down a bit the loading in more powerful devices.

**Comment by Jaifroid** [comment]
Hi @kelson42 , I've compiled an appxbundle of Kiwix JS Windows (not with the packaged WikiMed ZIM) with the svgSliceSize variable set to 2. Could you possibly follow these steps to test on your device?

1. Transfer a copy of `wikipedia_en_medicine_novid_2018-01.zim` to the phone, either with a USB cable,  microSD card, or by downloading from the Settings page of Kiwix JS Windows.

2. Uninstall Kiwix JS Windows from the device (no need to uninstall Wikivoyage or WikiMed -- we're just going to test with the generic app to avoid huge downloads, as we may need to test a few times with tweaked settings).

3. Download the .appxbundle (only 4MB) in this GitHub directory and note download location: 
https://github.com/kiwix/kiwix-js-windows/tree/master/AppPackages/KiwixWebApp_0.9.8.0_Test
For an optimal test, reboot the phone to clear RAM.

4. Open File Explorer app, locate .appxbundle, install the package.

5. Open the app, go to Settings and turn off "Remember last visited page" under Privacy settings (to prevent the startup loop in case of a crash).

6. Go back to Home page and search for Hodgkin and Huxley and open page.

Let me know if this allows the page to load correctly. Also, if it still crashes, does it crash before any text is shown, or straight after the page is shown, or after some delay? If not fixed, we can try reducing to one SVG per batch. I'll be testing also on a low-spec device I have.

**Comment by Jaifroid** [comment]
On an old Lumia 920 hacked to run Windows 10 Mobile (it has 1GB of memory), I need an svgSliceSize of 1 for this article not to crash. It crashes with 2.

An .appxbundle with svgSliceSize set to 1 is available here for testing:

https://github.com/kiwix/kiwix-js-windows/tree/master/AppPackages/KiwixWebApp_0.9.81.0_Test

**Comment by kelson42** [comment]
@Jaifroid Thank you for all the effort and testing. If it works for you then I do not think it makes much sense to make to test as my device has also exactly 1Gb of memory. Could you please make directly an update of the Windows store? Or maybe you want to make other fixes?

**Comment by Jaifroid** [comment]
I can update the app in the Store, but since updates take 24-48 hours (business days only), if there is an updated ZIM of WikiMed about to come out, it would make sense to wait for it. The last one came out on 5th Jan, so if we're getting a new one on Monday or Tuesday, I might as well include it in the submission.

Even better would be a new WikiMed with the LaTeX/MathJax strings intact.......!

**Comment by Jaifroid** [comment]
Oh, OK, so I'd better update the app next week then. I'm going to update Kiwix-JS-Windows vanilla app to 0.9.9 Beta at the same time (I'll post new CHANGELOG shortly). Wikivoyage can probably wait a while (no equations AFAIK!).

It's marginally slower when decompressing one SVG at a time, but on desktop I don't notice it at all, and I hardly notice it on the 950XL. It's well worth the trade-off to be able to support lower-spec models.

**Comment by Jaifroid** [comment]
@kelson42 No rush, but when you're able, please confirm that this bug is now squashed on your 1GB device (ensure the app has updated to 0.9.9 first -- it will inform you on first run after update, or check the About page). To hasten the download, go to Microsoft Store -> Hamburger menu -> Downloads and updates, and if necessary tap Get updates. It should be a small update (code only, the ZIM does not get downloaded again).

**Comment by kelson42** [comment]
@Jaifroid With last Wikimed the app does not crash anymore. But is true it is a bit slow to get all pictures/equations displayed. But it works! :)

**Comment by Jaifroid** [comment]
Thanks @kelson42 . Better slow than crashing! The slowness should *only* affect a page like this with lots of svg equations. Normal png/gif/jpeg pictures should be no problem for the app. With all image types it starts decompressing only the images in the current viewport, and then prefetches up to 20 images further down the page, then stops and waits for the user scrollstop before decompressing more.

Anyway, hopefully SVG equations will be a fallback only if you can get mw-offliner to include the MathJax strings again as alt text. I think that's essential for the maths wikis. It's 1000% faster to typeset with MathJax.
