### ISSUE TITLE
Opening geo links in page via the Windows Maps app

### ISSUE THREAD

**Issue by sharun-s** [kiwix/kiwix-js-windows#59]
I just came across this url mechanism to open geo links via the Windows Maps app 
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-maps-app

The Windows Maps app has offline maps support so it might be a useful (and cool) future feature. Basically click the geo link in the info box should pop open the windows app to that lat/long.

**Comment by Jaifroid** [comment]
Hi @sharun-s , this issue is already resolved in #31.. It's been in Kiwix-JS-Windows since December. Just click on any of the blue map markers in many Wikivoyage pages, and it will open the corresponding location in Windows Maps. It works completely offline if the user has downloaded the relevant map in the Windows offline maps setting. If the user hasn't downloaded the map, the maps app will need a connection. You can test this most easily with the Wikivoyage app - https://www.microsoft.com/store/apps/9N5SB90Q4JBJ .

Here is an example from the Delhi article:

![image](https://user-images.githubusercontent.com/4304337/38718680-2587e824-3ee6-11e8-8ac7-77beb6b9cf2f.png)

**Comment by sharun-s** [comment]
That's awesome! Can you link to where this change is? Basically is there some special conversion from geo:x,y to bingmaps:something? Was wondering if kiwix-js can open the url too...

**Comment by Jaifroid** [comment]
The code starts here:
https://github.com/kiwix/kiwix-js-windows/blob/master/www/js/app.js#L2075
Wikivoyage German and Wikivoyage English turned out to have slightly different ways of doing these links. They seem to be the main ones that use them.
In Kiwix JS we simply made sure that geo: links were clickable, generically, but Windows asks you to search for an app to display the link, as Bing Maps doesn't handle geo: links natively.
BTW, you can run Kiwix JS Windows in a browser in the same way as Kiwix JS, from file://. You don't need to install the app if you don't want to. It runs in Edge, IE and Firefox at least. So you can use debugging tools on it.

**Comment by Jaifroid** [comment]
PS Most up-to-date branch currently is master-dev https://github.com/kiwix/kiwix-js-windows/tree/master-dev

**Comment by sharun-s** [comment]
I am getting this weird pop up when I do "bingmaps:?collection=point."+lat+"_"+long 
![map](https://user-images.githubusercontent.com/18413274/38719842-9823cb2a-3f11-11e8-8a06-996bd1aa2fa8.png)

**Comment by Jaifroid** [comment]
You can assign the different parenthetical matches in a regular expression to the variables of a function. In that case I was using the p numbers to quickly number the parts. I could have been clearer and given them more expressive names!

**Comment by sharun-s** [comment]
Ok never mind I think I have to play around with the parameters. I'll close this issue. Thanks for the link!

**Comment by Jaifroid** [comment]
That popup is the info panel about the chosen place. You need to give the place a name, ideally, so that it doesn't just say "Collection Point".

**Comment by Jaifroid** [comment]
Sorry, I meant "Custom Pin".

**Comment by sharun-s** [comment]
Thanks!
