### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#72]
This is always a joy to see all the good work done on Kiwix JS Windows. That said, I think this work suffers of a small weakness which is the naming of the releases. Currently we have the "0.9.9.89 beta". This starts IMO to be a bit ridiculous, not only the name is really complicated and difficult to remember but the the software has reached a level of maturity which deserves IMO a version 1.0. Why not releasing 1.0 soon? and then stick to a X.Y.Z naming nomenclature?

**Comment by Jaifroid** [comment]
I agree! The problem is I've never quite felt that it's "ready" to come out of beta. When I first started coding this, I was learning a lot of things, and there is some very clunky code that I'd like to refactor (particularly the stylesheet caching system). I've always had in mind that a "Version 1.0" would have more streamlined code.

But maybe it's reached the point where I should release Version 1, and reserve refactoring for Version 2. Having said that, the release this morning was a bit of an emergency bug fix for a regression that stopped people using the download library, which is why I only incremented by 0.01!

**Comment by kelson42** [comment]
@Jaifroid The feeling that the software is not really finished and so not really ready for a 1.0... is a common feeling. There is nothing bad about it, it is mostly a sign of perfectionism. But being a bit pragmatic is not bad either. Kiwix JS Windows is good and if you are just before revamping a few things then this is the perfect moment to release 1.0. What I can recommend to you is to create a 1.0 milestone on Github, put in it all the tickets you believe are really important to fix for 1.0 and then stick to that (to avoid the "moving target" effect).

**Comment by kelson42** [comment]
I can only repeat what I said almost a year ago. IMO this is really ready for a 1.0. I really struggle to follow the dev with these big alpha/beta numbers.

**Comment by Jaifroid** [comment]
After 0.9.9.99, the next release will be 1.0 and no longer Beta. This gives me just three more beta releases, and since these are tied more or less to the release of Wikivoyage and WikiMed ZIMs, it won't be long now... 🙂

Version 2.0 will be a refactor that is much more closely based on PRs I am making to Kiwix JS upstream, either PRs I hope to be incorporated into master such as [Dark Mode](https://github.com/kiwix/kiwix-js/pull/582), or branches that implement certain features better than they are currently done on Kiwix JS Windows, such as caching using indexedDB or CacheAPI (instead of File System) as in [Persist cache in localSorage](https://github.com/kiwix/kiwix-js/tree/Persist-cache-in-localStorage). So, I have a plan...

**Comment by Jaifroid** [comment]
I feel that the current version (0.9.9.97) is now very close for what I would like for a 1.0 non-Beta version. The top and bottom toolbars now behave in the same way as in the Android app on both mobile and PC. I will now look through the remaining issues to see if any are urgent for the 1.0 release.

**Comment by Jaifroid** [comment]
@kelson42 Could I ask for a bit of quick advice? I would like to release an updated UWP app with ZSTD support. Is this a significant-enough step to warrant labelling the next release Version 1.0? The reason I am unsure is that there are a number of issues still left in my milestones for 1.0, which I won't have time to work on in the next few weeks. So would you recommend I renumber those milestones to 1.1, or should I release another interim, 0.9.9.994 beta with the ZSTD decompression?

**Comment by kelson42** [comment]
1.0.0 and then 1.0.1 or 1.1.0

**Comment by Jaifroid** [comment]
OK, thanks. I'll adopt the major.minor.patch convention. I'll release 1.0.0 next and bump the milestones to 1.1.0.

**Comment by Jaifroid** [comment]
Release 1.0.0 now in certification in the Store and available for sideloading from releases.
