### ISSUE TITLE
Increase apps visibility in Microsoft App store

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#77]
If I type "Wikipedia" in Microsoft App Store, none of our 3 apps are displayed. Can we fix that?

**Comment by Jaifroid** [comment]
@kelson42 In the Store listing for Kiwix JS Windows, I put "Wikipedia" as one of the seven search terms I'm allowed to have. These are the search terms:

* Wikipedia
* Wikimedia
* offline
* ZIM reader
* Gutenberg
* TED talks
* Wikivoyage

And the main App Description mentions Wikipedia in the first line.

("Kiwix" of course is in the title and all over the descriptions, so I didn't think it was necessary to add it as a search term.)

I guess the problem is that there are tons of Wikipedia rip-off apps (and some good ones) in the Store, so searching for just "Wikipedia" doesn't break through the noise.

**Comment by kelson42** [comment]
@Jaifroid What you say seems logicial to me, but I don't get "tons" of apps. Only 5 results:
* Wikio fro Wikipedia
* Wikini for Wikipedia
* Wikipedia WP8.1
* Wikipedia Reader
* Wikipedia Viewer

**Comment by Jaifroid** [comment]
I just did a search for "wikipedia" (no capital letter, because people don't bother) inside the Microsoft Store App on PC, on the Web of the Store, and inside the Store App on Mobile. The results are below. I wonder if it makes a difference that my system defaults to searching in the en-GB store? Note that because it's not in the top five, you have to click on "All apps" in some cases. On Mobile, you have to press the Search key, because the dropdown only shows the top five apps. It would be nice to move the app up into the top five!

Microsoft Store app on PC:

![image](https://user-images.githubusercontent.com/4304337/57979411-2b3f9580-7a15-11e9-8910-a30a6fc2be25.png)

Web (https://www.microsoft.com/en-gb/search/shop/apps?q=wikipedia) 

![image](https://user-images.githubusercontent.com/4304337/57979437-7d80b680-7a15-11e9-917e-33b7dee455c0.png)

Microsoft Store App on Mobile:

![image](https://user-images.githubusercontent.com/4304337/57979472-f08a2d00-7a15-11e9-8e98-61ade5406376.png)

**Comment by kelson42** [comment]
@Jaifroid I see indeed more, following your advices. So, after your explanations, not sure anymore if there is anything we can do to improve the situation.

**Comment by Jaifroid** [comment]
Hopefully this is now improved.
