### ISSUE TITLE
Automate publishing of app with Github actions CI

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js-windows#84]
Apps are currently manually built and published. We could/should automate publishing via Github actions CI. This would have following advantages:
* Not depending on a person to build it
* More robust as a robot does not make any manual errors
* More secure in a sense that a developer's computer is less trustable than a CI
* The release process been automated it is defacto documented
* Speed-up release and avoid additional manual work to put things on download.kiwix.org
* Considering that there is no CI at all for the moment on Kiwix-js-windows this would also offer an opportunity to introduce it for PR and secure the development process.

**Comment by Jaifroid** [comment]
I fully agree...

**Comment by Jaifroid** [comment]
Just to note here that a Cordova dev has managed to build, install and run a UWP app using GitHub actions CI here: https://github.com/apache/cordova-windows/issues/354#issuecomment-559611332. Looks promising.

**Comment by Jaifroid** [comment]
So far I've created these scripts:

* A [CI action](https://github.com/kiwix/kiwix-js-windows/blob/master/.github/workflows/CI.yml) that automates upload of the correct bundle to donwload.kiwix.org when a new UWP app is released (but the bundle must have been created first in Visual Studio)
* A [PowerShell script](https://github.com/kiwix/kiwix-js-windows/blob/master/scripts/Build_NWJS.ps1) that builds the three different flavours of the NWJS app (WinXP/Vista, ia32, ia64)
* A [PowerShell script](https://github.com/kiwix/kiwix-js-windows/blob/master/scripts/Create-DraftRelease.ps1) that, if given a new tag name (e.g. "v1.1.3"), drafts a new release of the UWP app and uploads the correct assets (if they exist) to GitHub releases using their REST API -- this script currently runs locally on a Windows machine, but can easily be turned into a GitHub action running on `windows-latest`

What is proving much trickier is a process to automate building of the `.appxupload` or `.appxbundle` files without using Visual Studio's build menu. `MSBuild.exe` fails when fed a `.jsproj` type, and building manually with `makeappx.exe` is extremely cumbersome and error-prone.

**Comment by Jaifroid** [comment]
An action to build a C++ UWP project is described here:

http://www.dotnetapp.com/github-actions-for-uwp-apps-the-good-and-the-bad-and-the-ugly/ 

Unfortunately it uses MSBuild.exe, which is not compatible with .`jsproj`.

**Comment by Jaifroid** [comment]
An update: I have created a [PowerShell script](https://github.com/kiwix/kiwix-js-windows/blob/master/scripts/Create-DraftRelease.ps1) that can build the UWP app from this repo automatically (and also Electron and NWJS versions, according to the tag name). It uses a version of MSBuild that is compatible with JS projects (effectively the version that comes with Visual Studio 2017), and VS 2017 needs to be installed on the building machine. The build currently happens on my local machine, and it produces a draft release on GitHub Releases with the assets attached. GitHub Actions provides a version of Windows with VS 2017 pre-installed, so it might be possible to run this via Actions now. Step by step!

**Comment by Jaifroid** [comment]
A major advance: I have now created a GitHub action that can autopublish the Linux versions of the app (.AppImage, .deb, .rpm) on each push to master. The workflow is as follows:

* Set the version number in `package.json` and in the app, making sure they match;
* Create a draft release using the same version number (prefixed by `v`) as the draft tag;
* Push `package.json` (and any other changes) to master.

The action detects that there is a matching draft release, and will build the artefacts on latest Ubuntu and attach them to the draft release. If there is no matching draft, the action does not publish anything.

In principle, I should be able to build for Windows with the same procedure, but there is the added complication of code signing, adding the secret to the Repo, etc., so that is for another time.

Caveat: this only works currently for the base app, not for WikiMed or Wikivoyage. Reason: the ZIM archives for WikiMed and Wikivoyage are too large to publish to GitHub, so the CI doesn't have access to them at build time.

 ```
 • building        target=AppImage arch=ia[32](https://github.com/kiwix/kiwix-js-windows/runs/5387981841?check_suite_focus=true#step:5:32) file=bld/Electron/Kiwix JS Electron-1.9.3-E-i386.AppImage
  • building        target=deb arch=ia32 file=bld/Electron/kiwix-js-electron_1.9.3-E_i386.deb
  • publishing      publisher=Github (owner: kiwix, project: kiwix-js-windows, version: 1.9.3-E)
  • uploading       file=Kiwix-JS-Electron-1.9.3-E-i386.AppImage provider=GitHub
  • building        target=deb arch=x64 file=bld/Electron/kiwix-js-electron_1.9.3-E_amd64.deb
  • uploading       file=Kiwix-JS-Electron-1.9.3-E.AppImage provider=GitHub
  • building        target=rpm arch=ia32 file=bld/Electron/kiwix-js-electron-1.9.3-E.i686.rpm
  • uploading       file=kiwix-js-electron_1.9.3-E_i[38](https://github.com/kiwix/kiwix-js-windows/runs/5387981841?check_suite_focus=true#step:5:38)6.deb provider=GitHub
  • building        target=rpm arch=x64 file=bld/Electron/kiwix-js-electron-1.9.3-E.x86_64.rpm
  • uploading       file=kiwix-js-electron_1.9.3-E_amd64.deb provider=GitHub
  • uploading       file=kiwix-js-electron-1.9.3-E.i686.rpm provider=GitHub
  • uploading       file=kiwix-js-electron-1.9.3-E.x86_64.rpm provider=GitHub
```

**Comment by Jaifroid** [comment]
The Windows Electron version is now also being built by CI, and the CI is now producing automated nightly builds (see screenshot). In principle, only two things are now missing to complete this issue:

* Build the NWJS app programmatically. This is now only really targeted at Windows XP and Vista users. This is achievable, but I'm not sure if it's worth the effort because I'm considering deprecation. See #237.
* Build the UWP app automatically. This is more challenging because it requires Visual Studio 2017, and Microsoft is removing from GitHub the only Windows version (Windows Server 2016) that had this package, as of 15th March. I have added comments to [the deprecation issue](https://github.com/actions/virtual-environments/issues/4312) and to [calls for providing VS 2017](https://github.com/actions/virtual-environments/issues/5177) alongside VS 2019 in the Windows Server 2019 runner. I don't know if there's an alternative solution for this. Unfortunately JSPROJ types are no longer supported in VS 2019 and VS 2022, and more modern build targets don't support Windows Mobile any more. 

Since both of the above have question marks over them, I'm closing the issue for now. If anyone wants to test nightly builds, they can do so with the Electron app.

![image](https://user-images.githubusercontent.com/4304337/157390355-790224db-6988-4527-af90-d8c20a15c0f8.png)
